### ISSUE TITLE
Using with MoveNet/PoseNet pose estimation

### ISSUE THREAD

**Issue by benank** [google-coral/webcoral#4]
### Description

Hello, I'm wondering how this repo can be used with [MoveNet](https://github.com/google-coral/pycoral/blob/master/examples/movenet_pose_estimation.py). Currently it looks like it only supports models with classification output or detection output (with a specific format: list of objects with id, score, and bbox). Is there a way to allow support for MoveNet/PoseNet models? 

I've been trying to make it work but I don't know how to parse the output buffers and use `Module.HEAPF32...`. I haven't been able to find any documentation online about the `Module.HEAPF32`. either. For reference, [this is what the output looks like](https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/README.md#pose-estimation) from MoveNet or similar models. I've also looked at how the [python PoseNet repo](https://github.com/google-coral/project-posenet/blob/master/pose_engine.py) does it, but I haven't been able to convert it into the javscript equivalent yet.

Do you have any suggestions on how to get started on adding this capability? 

My goal is to run MoveNet through the wasm module using WebUSB with the Coral Accelerator. I'd love to be able to run pose detection on multiple people in realtime.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support, Feature Request

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by Naveen-Dodda** [comment]
@benank, seems like you question is more around details of Movenet inference on edgettpu. 

Movenet doesn't have a special decoder like posenet. Parsing output of MoveNet is straight forward You can look at the example here (https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/movenet.ipynb).

As long as you initiate your tflite interpreter with libedgetpu; you should be able run movenet on Coral accelerator.

**Comment by benank** [comment]
I see, thanks for the info @Naveen-Dodda! That's very helpful and I think I'm good to go now.
