### ISSUE TITLE
No DFU capable USB device available

### ISSUE THREAD

**Issue by johnnymule** [google-coral/webcoral#5]
### Description

Running into the following while flashing the firmware.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Relevant Log Output

```shell
# make reset
third_party/dfu-util/src/dfu-util \
    -D third_party/libedgetpu/driver/usb/apex_latest_single_ep.bin \
    -d 1a6e:089a -R || true
dfu-util 0.11-dev

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Warning: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release
dfu-util: No DFU capable USB device available
```
</details>

**Comment by hjonnala** [comment]
> ```shell
> # make reset
> third_party/dfu-util/src/dfu-util \
>     -D third_party/libedgetpu/driver/usb/apex_latest_single_ep.bin \
>     -d 1a6e:089a -R || true
> dfu-util 0.11-dev
> 
> Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
> Copyright 2010-2021 Tormod Volden and Stefan Schmidt
> This program is Free Software and has ABSOLUTELY NO WARRANTY
> Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
> 
> dfu-util: Warning: Invalid DFU suffix signature
> dfu-util: A valid DFU suffix will be required in a future dfu-util release
> dfu-util: No DFU capable USB device available
> ```

it is expected when `lsusb` output has` Bus 002 Device 006: ID 18d1:9302 Google Inc. `
