### ISSUE TITLE
error on make reset

### ISSUE THREAD

**Issue by Alpin38** [google-coral/webcoral#7]
hello 
i' have this error when a make the request   => make reset

"checking for libusb_init in -lusb... no
./configure: line 3951: syntax error near unexpected token `USB,'
./configure: line 3951: `    PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0.0,,'
make: *** [Makefile:64 : third_party/dfu-util/src/dfu-util] Erreur 2

i'm on debaian 11   (new install) 

can you help me ?

**Comment by hbak** [comment]
```
sudo apt install dfu-util
dfu-util -D third_party/libedgetpu/driver/usb/apex_latest_single_ep.bin -d 1a6e:089a 
```

This does what `make reset` does (look inside Makefile) except instead of attempting to compile dfu-util from submodule  source (which is where the error occurs) it installs it using apt.
